"use client";
import { useEffect, useMemo, useState } from "react";
import { formatTime, generateTimeOptions, isSlotAvailable } from "@/lib/availability";
import type { AvailabilityBlock, Court } from "@/lib/types";
const today = () => new Date().toISOString().slice(0, 10);
export function AvailabilityBoard() {
  const [date, setDate] = useState(today()); const [courts, setCourts] = useState<Court[]>([]); const [blocks, setBlocks] = useState<AvailabilityBlock[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); fetch(`/api/courts?date=${date}`).then(r => r.json()).then(d => { setCourts((d.courts ?? []).map((c: any) => ({ id: c.id, name: c.name, hourlyRate: c.hourly_rate, status: c.status }))); setBlocks((d.blocks ?? []).map((b: any) => ({ courtId: b.court_id, startsAt: b.starts_at, endsAt: b.ends_at, kind: b.kind }))); }).finally(() => setLoading(false)); }, [date]);
  const times = useMemo(() => generateTimeOptions(date, "00:00", "24:00").filter(t => new Date(t) > new Date()), [date]);
  return <><label className="mb-5 block w-fit text-sm font-semibold text-ash">Date<input type="date" min={today()} value={date} onChange={e => setDate(e.target.value)} className="ml-3 rounded-card border border-line bg-surface px-3 py-2 text-ink" /></label>{loading ? <p className="text-ash">Checking courts…</p> : <div className="grid gap-3 lg:grid-cols-2">{courts.map(court => { const free = times.filter(start => isSlotAvailable(blocks, court.id, start, new Date(new Date(start).getTime() + 3_600_000).toISOString())); return <article key={court.id} className="rounded-card border border-line bg-surface p-4 shadow-card"><div className="flex items-center justify-between"><h2 className="font-display text-xl font-bold">{court.name}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${court.status === "active" ? "bg-court/10 text-court" : "bg-clay/10 text-clay"}`}>{court.status === "active" ? `${free.length} slots free` : court.status}</span></div>{court.status === "active" ? free.length ? <div className="mt-3 flex flex-wrap gap-2">{free.map(t => <span key={t} className="rounded-card bg-chalk px-2.5 py-1.5 text-sm font-medium text-court">{formatTime(t)}</span>)}</div> : <p className="mt-3 text-sm text-clay">No one-hour slots available.</p> : <p className="mt-3 text-sm text-ash">This court is not bookable.</p>}</article>; })}</div>}</>;
}
