"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { formatPeso } from "@/lib/pricing";
import { formatTime, formatDate } from "@/lib/availability";
type Reservation = { booking_number: string; starts_at: string; ends_at: string; total_amount: number; courts: { name: string } | null };

export function Checkout({ reservationId, token }: { reservationId: string; token: string }) {
  const [reservation, setReservation] = useState<Reservation | null>(null);
  const [method, setMethod] = useState<"gcash" | "bank_transfer">("gcash");
  const [referenceNumber, setReferenceNumber] = useState("");
  const [proof, setProof] = useState<File | null>(null);
  const [message, setMessage] = useState("");
  const [submitted, setSubmitted] = useState(false);
  useEffect(() => { fetch(`/api/checkout?reservationId=${reservationId}&token=${token}`).then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error); setReservation(d.reservation); }).catch(e => setMessage(e.message)); }, [reservationId, token]);
  async function submit(e: React.FormEvent) { e.preventDefault(); if (!proof) return setMessage("Attach your payment screenshot."); setMessage(""); const form = new FormData(); form.set("reservationId", reservationId); form.set("token", token); form.set("method", method); form.set("referenceNumber", referenceNumber); form.set("proof", proof); const r = await fetch("/api/checkout", { method: "POST", body: form }); const d = await r.json(); if (!r.ok) return setMessage(d.error); setSubmitted(true); }
  if (!reservation) return <main className="mx-auto max-w-md p-6 text-center text-ash">{message || "Loading secure checkout…"}</main>;
  const summary = <div className="my-5 space-y-2 rounded-card border border-line bg-chalk p-4 text-sm"><p className="font-semibold">{reservation.booking_number} · {reservation.courts?.name}</p><p>{new Date(reservation.starts_at).toLocaleDateString("en-PH", { timeZone: "Asia/Manila", weekday: "long", month: "long", day: "numeric", year: "numeric" })}</p><p>{formatTime(reservation.starts_at)} – {formatTime(reservation.ends_at)}</p><p className="score-num text-2xl text-court">{formatPeso(reservation.total_amount)}</p></div>;
  if (submitted) return <main className="mx-auto max-w-md p-4 sm:pt-10"><section className="rounded-card border border-line bg-surface p-6 text-center shadow-card"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-court text-2xl text-white">✓</div><p className="mt-4 text-sm font-semibold uppercase tracking-[0.14em] text-court">Payment submitted</p><h1 className="mt-1 font-display text-2xl font-bold">You&apos;re nearly on court.</h1>{summary}<p className="text-sm text-ash">Our staff will check your payment proof. Once verified, your booking becomes confirmed.</p><div className="mt-6 space-y-2"><Link href="/" className="block w-full rounded-card bg-court py-3 font-semibold text-white">Back to booking</Link><Link href="/my-bookings" className="block w-full rounded-card border border-line py-3 font-semibold text-court">My bookings</Link></div></section></main>;
  return <main className="mx-auto max-w-md p-4 sm:pt-10"><div className="mb-3"><Link href="/" className="text-sm font-semibold text-court hover:underline">← Back to courts</Link></div><div className="rounded-card border border-line bg-surface p-5 shadow-card"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-court">Step 2 of 3 · Payment</p><h1 className="mt-1 font-display text-2xl font-bold">Complete your booking</h1>{summary}<form onSubmit={submit} className="space-y-4"><fieldset><legend className="mb-2 text-sm font-medium">Choose payment method</legend><div className="grid grid-cols-2 gap-2"><label className={`rounded-card border p-3 text-center text-sm font-semibold ${method === "gcash" ? "border-court bg-court/5 text-court" : "border-line"}`}><input className="sr-only" type="radio" checked={method === "gcash"} onChange={() => setMethod("gcash")} />GCash</label><label className={`rounded-card border p-3 text-center text-sm font-semibold ${method === "bank_transfer" ? "border-court bg-court/5 text-court" : "border-line"}`}><input className="sr-only" type="radio" checked={method === "bank_transfer"} onChange={() => setMethod("bank_transfer")} />Bank transfer</label></div></fieldset><div className="rounded-card border border-ball bg-ball/10 p-3 text-sm"><p className="font-semibold">Send {formatPeso(reservation.total_amount)} to {method === "gcash" ? "GCash" : "Bank transfer"}</p><p className="mt-1">{method === "gcash" ? "Pickleball Club · 0917 000 0000" : "Your Bank · Pickleball Club · 0000-0000-0000"}</p></div><label className="block text-sm font-medium">Payment reference number<input required value={referenceNumber} onChange={e => setReferenceNumber(e.target.value)} placeholder="Enter reference number" className="mt-1 w-full rounded-card border border-line px-3 py-2.5 font-normal" /></label><label className="block text-sm font-medium">Payment screenshot<input required type="file" accept="image/png,image/jpeg,image/webp" onChange={e => setProof(e.target.files?.[0] ?? null)} className="mt-1 block w-full text-sm font-normal" /></label><button className="w-full rounded-card bg-court py-3 font-semibold text-white hover:bg-court-light">Submit for verification →</button></form>{message && <p className="mt-4 rounded-card bg-clay/10 p-3 text-center text-sm text-clay">{message}</p>}</div></main>;
}
